### ISSUE TITLE
[Krb5LoginModule] authentication failed null (68)

### ISSUE THREAD

**Issue by karangarathi** [kwart/spnego-demo#5]
Hi, 
i have setup this spnego-demo project, and has configured all the required configuration. 

Still i get the authentication fail.  Please advise.
Below is the error which i get in console. 

15:40:24,693 INFO  [stdout] (http-localhost-127.0.0.1-8080-3) Refreshing Kerberos configuration

15:40:26,935 INFO  [stdout] (http-localhost-127.0.0.1-8080-3) 		[Krb5LoginModule] authentication failed 
15:40:26,936 INFO  [stdout] (http-localhost-127.0.0.1-8080-3) null (68)

15:40:26,946 ERROR [org.jboss.security.authentication.JBossCachedAuthenticationManager] (http-localhost-127.0.0.1-8080-3) Login failure: javax.security.auth.login.LoginException: null (68)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Unknown Source) [rt.jar:1.7.0_79]
	at com.sun.security.auth.module.Krb5LoginModule.login(Unknown Source) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.access$000(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) [rt.jar:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.invokePriv(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.login(Unknown Source) [rt.jar:1.7.0_79]
	at org.jboss.security.negotiation.spnego.SPNEGOLoginModule.getServerSubject(SPNEGOLoginModule.java:282) [jboss-negotiation-spnego-2.2.0.SP1.jar:2.2.0.SP1]
	at org.jboss.security.negotiation.spnego.SPNEGOLoginModule.spnegoLogin(SPNEGOLoginModule.java:235) [jboss-negotiation-spnego-2.2.0.SP1.jar:2.2.0.SP1]
	at org.jboss.security.negotiation.spnego.SPNEGOLoginModule.innerLogin(SPNEGOLoginModule.java:194) [jboss-negotiation-spnego-2.2.0.SP1.jar:2.2.0.SP1]
	at org.jboss.security.negotiation.spnego.SPNEGOLoginModule.login(SPNEGOLoginModule.java:137) [jboss-negotiation-spnego-2.2.0.SP1.jar:2.2.0.SP1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.invoke(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.access$000(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) [rt.jar:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.invokePriv(Unknown Source) [rt.jar:1.7.0_79]
	at javax.security.auth.login.LoginContext.login(Unknown Source) [rt.jar:1.7.0_79]
	at org.jboss.security.authentication.JBossCachedAuthenticationManager.defaultLogin(JBossCachedAuthenticationManager.java:449) [picketbox-infinispan-4.0.7.Final.jar:4.0.7.Final]
	at org.jboss.security.authentication.JBossCachedAuthenticationManager.proceedWithJaasLogin(JBossCachedAuthenticationManager.java:383) [picketbox-infinispan-4.0.7.Final.jar:4.0.7.Final]
	at org.jboss.security.authentication.JBossCachedAuthenticationManager.authenticate(JBossCachedAuthenticationManager.java:371) [picketbox-infinispan-4.0.7.Final.jar:4.0.7.Final]
	at org.jboss.security.authentication.JBossCachedAuthenticationManager.isValid(JBossCachedAuthenticationManager.java:160) [picketbox-infinispan-4.0.7.Final.jar:4.0.7.Final]
	at org.jboss.as.web.security.JBossWebRealm.authenticate(JBossWebRealm.java:214) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.security.negotiation.NegotiationAuthenticator.authenticate(NegotiationAuthenticator.java:187) [jboss-negotiation-common-2.2.0.SP1.jar:2.2.0.SP1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:455) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
	at java.lang.Thread.run(Unknown Source) [rt.jar:1.7.0_79]
Caused by: KrbException: null (68)
	at sun.security.krb5.KrbAsRep.<init>(Unknown Source) [rt.jar:1.7.0_79]
	at sun.security.krb5.KrbAsReqBuilder.send(Unknown Source) [rt.jar:1.7.0_79]
	at sun.security.krb5.KrbAsReqBuilder.action(Unknown Source) [rt.jar:1.7.0_79]
	... 44 more
Caused by: KrbException: Identifier doesn't match expected value (906)
	at sun.security.krb5.internal.KDCRep.init(Unknown Source) [rt.jar:1.7.0_79]
	at sun.security.krb5.internal.ASRep.init(Unknown Source) [rt.jar:1.7.0_79]
	at sun.security.krb5.internal.ASRep.<init>(Unknown Source) [rt.jar:1.7.0_79]
	... 47 more

**Comment by MouradHRM** [comment]
Hello @kkgujjar I'm encountering the same issue right now. Could you solve it by the time you wrote you comment ?
Thank you in advance

**Comment by kwart** [comment]
Have you tried to run the `run.sh` and then `run-browser.sh` scripts? They should work.
(The environment config is in `set-env.sh`.)
Which application server version do you use?
